### ISSUE TITLE
Coffee purchase logging

### ISSUE THREAD

**Issue by heyjaywilson** [CCTPlus/coffeetracker#57]
As a user I want to keep track of the coffee I've bought to brew at home. There are different types of coffee I can buy like
- pods
- beans
- grounds
- frozen
- concentrate
- etc...

There are different sizes and quantities in each. Example: A box of HEB K-cup of San Antonio Blend 12ct vs a Bag of HEB San Antonio blend 12oz whole bean

I want to be able to attach a photo of what I bought
I want to be able to add a note to what I bought
I want to be able to rate what I bought on a 5 point rating
I want to be able to quickly indicate if I should buy this again or not
```[tasklist]
### Tasks
- [ ] https://github.com/CCTPlus/coffeetracker/issues/58
- [ ] https://github.com/CCTPlus/coffeetracker/issues/59
- [ ] https://github.com/CCTPlus/coffeetracker/issues/60
```
