### ISSUE TITLE
Bean logging

### ISSUE THREAD

**Issue by heyjaywilson** [CCTPlus/coffeetracker#63]
```[tasklist]
### Tasks
- [ ] https://github.com/CCTPlus/coffeetracker/issues/66
- [ ] https://github.com/CCTPlus/coffeetracker/issues/67
- [ ] https://github.com/CCTPlus/coffeetracker/issues/68
```
